config/routes.rb
Gumbulanya::Application.routes.draw do
 
  resources :visits

  resources :users

  resources :clinicians

  resources :clinics
  
  get "home/index"
  match ''=> 'home#index'  
  

  root :to => 'home#index'

end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
# Validations
	validates :name,  :presence => true
	validates :phone, :presence => true,
                    :length => { :is => 8 },
                    :numericality => { :only_integer => true }
        validates :email, :uniqueness => true, :presence => true           
# Associations 
# Create a join table in visits with a foreign key to clinics 
# and clinicians 
	has_many :visits
	has_many :clinicians , :through => :visits

end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  # GET /clinics
  # GET /clinics.json
  def index
    @clinics = Clinic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clinics }
    end
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
    @clinic = Clinic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clinic }
    end
  end

  # GET /clinics/new
  # GET /clinics/new.json
  def new
    @clinic = Clinic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clinic }
    end
  end

  # GET /clinics/1/edit
  def edit
    @clinic = Clinic.find(params[:id])
  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(params[:clinic])

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to @clinic, notice: 'Clinic was successfully created.' }
        format.json { render json: @clinic, status: :created, location: @clinic }
      else
        format.html { render action: "new" }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clinics/1
  # PUT /clinics/1.json
  def update
    @clinic = Clinic.find(params[:id])

    respond_to do |format|
      if @clinic.update_attributes(params[:clinic])
        format.html { redirect_to @clinic, notice: 'Clinic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic = Clinic.find(params[:id])
    @clinic.destroy

    respond_to do |format|
      format.html { redirect_to clinics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_form.html.erb
<%= form_for(@clinic) do |f| %>
  <% if @clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinic.errors.count, "error") %> prohibited this clinic from being saved:</h2>

      <ul>
      <% @clinic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.telephone_field :phone %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.telephone_field :fax %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clinics/edit.html.erb
<h1>Editing clinic</h1>

<%= render 'form' %>

<%= link_to 'Show', @clinic %> |
<%= link_to 'Back', clinics_path %>

app/views/clinics/index.html.erb
<h1>Listing clinics</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Fax</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clinics.each do |clinic| %>
  <tr>
    <td><%= clinic.name %></td>
    <td><%= clinic.address %></td>
    <td><%= clinic.phone %></td>
    <td><%= clinic.fax %></td>
    <td><%= clinic.email %></td>
    <td><%= link_to 'Show', clinic %></td>
    <td><%= link_to 'Edit', edit_clinic_path(clinic) %></td>
    <td><%= link_to 'Destroy', clinic, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Clinic', new_clinic_path %>

app/views/clinics/new.html.erb
<h1>New clinic</h1>

<%= render 'form' %>

<%= link_to 'Back', clinics_path %>

app/views/clinics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @clinic.name %>
</p>

<p>
  <b>Address:</b>
  <%= @clinic.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @clinic.phone %>
</p>

<p>
  <b>Fax:</b>
  <%= @clinic.fax %>
</p>

<p>
  <b>Email:</b>
  <%= @clinic.email %>
</p>


<%= link_to 'Edit', edit_clinic_path(@clinic) %> |
<%= link_to 'Back', clinics_path %>