config/routes.rb
Gumbulanya::Application.routes.draw do
 
  resources :visits

  resources :users

  resources :clinicians

  resources :clinics
  
  get "home/index"
  match ''=> 'home#index'  
  

  root :to => 'home#index'

end

app/models/visit.rb
class Visit < ActiveRecord::Base
# Associations 
# Create a join table in visits with a foreign key to clinics 
# and clinicians 
	belongs_to :clinic
	belongs_to :clinician
	
# Use event_calendar plugin to display visits spanning multiple days 
	has_event_calendar

# Validations
# some custom validators
	validate :start_at_cannot_be_in_the_past,
	:end_at_cannot_be_before_start_date
 
  def start_at_cannot_be_in_the_past
    if !start_at.blank? and start_at < Date.today
      errors.add(:start_at, "can't be in the past")
    end
  end
 
  def end_at_cannot_be_before_start_date
  	  if end_at < start_at
  	  	  errors.add(:end_at, "can't be earlier than start date")
    end
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # GET /visits
  # GET /visits.json
  def index
  	  # View variables	  
    @visits = Visit.all
    @date = Date.today 
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visits }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])
    @clinic = Visit.find(params[:id]).clinic_id
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    @visit = Visit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(params[:visit])

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_at %>
  </div>
  <div class="field">
    <%= f.label :clinic %><br />
    <%= f.collection_select(:clinic_id, Clinic.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :clinician %><br />
    <%= f.collection_select(:clinician_id, Clinician.all, :id, :family_name)  %>
  </div>

  <div class="field">
    <%= f.label :Visit_details %><br />
    <%= f.text_field :name  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>


<table>
  <tr>
    <th>Start date</th>
    <th>End date</th>
    <th>Clinic</th>
    <th>Visitor</th>
    <th></th>
  </tr>

<% @visits.each do |visit| %>
  <tr>
    <td><%= visit.start_at %></td>
    <td><%= visit.end_at %></td>
    <td><%= Clinic.find(visit.clinic_id).name %></td>
    <td><%= Clinician.find(visit.clinician_id).family_name %></td>

    <td><%= link_to 'Show', visit %></td>
    <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
    <td><%= link_to 'Destroy', visit, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start date:</b>
  <%= @visit.start_at %>
</p>

<p>
  <b>End date:</b>
  <%= @visit.end_at %>
</p>

<p>
  <b>Clinic:</b>
  <%= Clinic.find(@visit.clinic_id).name %>
</p>

<p>
  <b>Clinician:</b>
  <%= Clinician.find(@visit.clinician_id).family_name %>
</p>


<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>