config/routes.rb
Gumbulanya::Application.routes.draw do
 
  resources :visits

  resources :users

  resources :clinicians

  resources :clinics
  
  get "home/index"
  match ''=> 'home#index'  
  

  root :to => 'home#index'

end

app/models/clinician.rb
class Clinician < ActiveRecord::Base
# Validations 
# note the email feild already does some format checking 
	validates :family_name,  :presence => true
	validates :given_name,  :presence => true
	validates :phone, :presence => true,
                    :length => { :is => 8 },
                    :numericality => { :only_integer => true }
        validates :email, :uniqueness => true, :presence => true           
	
# Associations 
# Create a join table in visits with a foreign key to clinics 
# and clinicians 
	has_many :visits
	has_many :clinics , :through => :visits	
	
end

app/controllers/clinicians_controller.rb
class CliniciansController < ApplicationController
  # GET /clinicians
  # GET /clinicians.json
  def index
    @clinicians = Clinician.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clinicians }
    end
  end

  # GET /clinicians/1
  # GET /clinicians/1.json
  def show
    @clinician = Clinician.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clinician }
    end
  end

  # GET /clinicians/new
  # GET /clinicians/new.json
  def new
    @clinician = Clinician.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clinician }
    end
  end

  # GET /clinicians/1/edit
  def edit
    @clinician = Clinician.find(params[:id])
  end

  # POST /clinicians
  # POST /clinicians.json
  def create
    @clinician = Clinician.new(params[:clinician])

    respond_to do |format|
      if @clinician.save
        format.html { redirect_to @clinician, notice: 'Clinician was successfully created.' }
        format.json { render json: @clinician, status: :created, location: @clinician }
      else
        format.html { render action: "new" }
        format.json { render json: @clinician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clinicians/1
  # PUT /clinicians/1.json
  def update
    @clinician = Clinician.find(params[:id])

    respond_to do |format|
      if @clinician.update_attributes(params[:clinician])
        format.html { redirect_to @clinician, notice: 'Clinician was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clinician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinicians/1
  # DELETE /clinicians/1.json
  def destroy
    @clinician = Clinician.find(params[:id])
    @clinician.destroy

    respond_to do |format|
      format.html { redirect_to clinicians_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clinicians_helper.rb
module CliniciansHelper
end

app/views/clinicians/_form.html.erb
<%= form_for(@clinician) do |f| %>
  <% if @clinician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinician.errors.count, "error") %> prohibited this clinician from being saved:</h2>

      <ul>
      <% @clinician.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :given_name %><br />
    <%= f.text_field :given_name %>
  </div>
  <div class="field">
    <%= f.label :family_name %><br />
    <%= f.text_field :family_name %>
  </div>
    <div class="field">
    <%= f.label :specialty %><br />
    <%= f.text_field :specialty %>
  </div>
    <div class="field">
    <%= f.label :display_colour %><br />
    <%= f.text_field :display_colour %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.telephone_field :phone %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.telephone_field :fax %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clinicians/edit.html.erb
<h1>Editing clinician</h1>

<%= render 'form' %>

<%= link_to 'Show', @clinician %> |
<%= link_to 'Back', clinicians_path %>

app/views/clinicians/index.html.erb
<h1>Listing clinicians</h1>

<table>
  <tr>
    <th>Given name</th>
    <th>Family name</th>
    <th>Address</th>
    <th>Specialty</th>
    <th>Colour</th>
    <th>Phone</th>
    <th>Fax</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clinicians.each do |clinician| %>
  <tr>
    <td><%= clinician.given_name %></td>
    <td><%= clinician.family_name %></td>
    <td><%= clinician.address %></td>
    <td><%= clinician.specialty %></td>
    <td><%= clinician.display_colour %></td>
    <td><%= clinician.phone %></td>
    <td><%= clinician.fax %></td>
    <td><%= clinician.email %></td>
    <td><%= link_to 'Show', clinician %></td>
    <td><%= link_to 'Edit', edit_clinician_path(clinician) %></td>
    <td><%= link_to 'Destroy', clinician, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Clinician', new_clinician_path %>

app/views/clinicians/new.html.erb
<h1>New clinician</h1>

<%= render 'form' %>

<%= link_to 'Back', clinicians_path %>

app/views/clinicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Given name:</b>
  <%= @clinician.given_name %>
</p>

<p>
  <b>Family name:</b>
  <%= @clinician.family_name %>
</p>

<p>
  <b>Address:</b>
  <%= @clinician.address %>
</p>

<p>
  <b>Specialty:</b>
  <%= @clinician.specialty %>
</p>

<p>
  <b>Colour:</b>
  <%= @clinician.display_colour %>
</p>

<p>
  <b>Phone:</b>
  <%= @clinician.phone %>
</p>

<p>
  <b>Fax:</b>
  <%= @clinician.fax %>
</p>

<p>
  <b>Email:</b>
  <%= @clinician.email %>
</p>


<%= link_to 'Edit', edit_clinician_path(@clinician) %> |
<%= link_to 'Back', clinicians_path %>